# Generated by Django 5.0.1 on 2024-01-24 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthchecks', '0002_alter_typehealthchecks_type_health_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifications', models.CharField(max_length=50)),
                ('access_time', models.IntegerField()),
                ('created_in', models.DateTimeField()),
                ('date_start_exams', models.DateField()),
                ('date_end_exams', models.DateField()),
                ('token', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
